title: Cenfracee Pvt Ltd
description: Resource technology for a smarter Sri Lanka. Flash chemistry, advanced electrochemistry, mining, and printed photovoltaics.
baseurl: ""
url: "https://cenfracee.lk"
permalink: /blog/:title/

# Build settings
markdown: kramdown
